- hosts: all
  become: true

  tasks:
    - name: Update cache
      apt:
        update_cache: yes
    
    - name: Ensure git is installed
      apt:
        pkg: git

    - name: Ensure docker is installed
      apt:
        pkg: docker.io


    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
